### ISSUE TITLE
Boot stuck at Loading Hurd...

### ISSUE THREAD

**Issue by oaken-source** [flavioc/cross-hurd#11]
I've followed the instructions in the README, but the boot appears to be stuck. grub comes up, and Mach starts, but then it remains on the following output:

```
  Booting `GNU'      
                     
Loading GNU Mach     
Loading the Hurd ... 
```

Any Idea what I could try to debug this?

**Comment by z3ntu** [comment]
On my build this line is hanging during the first boot https://github.com/flavioc/cross-hurd/blob/357531a73e257b761f7c39719a9ef42c8e85bc6f/files/SETUP#L37

If you add a `-v` after `MAKEDEV` then you see that it hangs at `settrans -g -c null` (part of the `std` group of translators that the script is setting up)
@flavioc Can you try and see if it works for you on the latest sources?

**Comment by z3ntu** [comment]
Made a working build now :)

![image](https://user-images.githubusercontent.com/3768500/126903747-c76997c5-ca30-4c0e-add6-23ad3b40c3ae.png)

I did upgrade some dependencies and pinned glibc to the latest stable, maybe that fixed it.
