### ISSUE TITLE
Passing -enable-kvm to qemu causes reboots.

### ISSUE THREAD

**Issue by BioMike** [flavioc/cross-hurd#16]
Thank you for the recent updates, it finally caused me to build and boot the image into a workable system. I however found a few problems, this being one of them.

I have also a Debian Hurd image, that I load through qemu. However if I pass the same command line to load the cross-hurd image it causes a boot loop. First mach is loaded and after that it tries to load the Hurd, but fails without any output and causes it to reboot qemu (qemu bios is reinitialized). Removing the -enable-kvm flag from the command line solves this issue, but results in a slower system.

Expected solution: being able to use '-enable-kvm' to load the image.

**Comment by flavioc** [comment]
That's interesting. It seems like it doesn't even start gnumach. Probably have to spent more time looking into this to figure out the root cause.

**Comment by flavioc** [comment]
Indeed
