### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by Elethiomel** [flavioc/cross-hurd#19]
On first boot I'm asked for a password which I enter.

After the reboot, entering the correct password for root yields:

`"login: Authentication Failure: Operation not permitted"`

Entering a wrong password yields:

`"login: Invalid Password"`

**Comment by Elethiomel** [comment]
After some poking around by booting with init=/bin/bash I found a few things.

The first was that every file was owned by uid 1000 (the uid of my user on the host system I used to build). 
A recursive chown of / to root:root did nothing to fix this. Upon a reboot I still couldn't log in.
I did notice however that the uid /hurd/password was running under was 1000 when I got back under the init trick. Every other process was running under uid 0. Somehow the uid was getting baked in from the uid of the builder.

I decided to try a build of the system as **root** and what do you know? It worked! I could enter a password on setup and then login using that password after the reboot!

**Comment by flavioc** [comment]
Thanks for looking into this!

I think this happened once I tried to ensure most of the scripts could be run without root requiring root. I've changed the scripts to change the owner to root once they are copied into mount/ and that seems to do the trick.
