### ISSUE TITLE
Compatibility of cross-compiled binaries?

### ISSUE THREAD

**Issue by johnsonjh** [flavioc/cross-hurd#21]
This may not a bug, and if so, I apologize for wasting your time. 

Using the cross-compiler produced by cross-hurd, the resulting dynamic binaries won't run properly on Debian GNU/Hurd (Unofficial hurd-i386 20230607-22:16), and terminate with a very unhelpful error message:

![Screenshot from 2023-08-05 17-13-54](https://github.com/flavioc/cross-hurd/assets/61629094/0f36f525-481f-4566-bbd3-4c545e64b0f4)

If I cross-build static binaries, they *mostly* work, but some functionality is broken, for example, `clock_gettime` is broken (and problems with dlopen, etc. but that is to be expected when static linking glibc binaries).

The same code built natively using GCC on Debian GNU/Hurd 2023 works fine, without any issues.

Is this due to a (subtle?) ABI mismatch, and to be expected?  The glibc version in Debian is 2.36, same as cross-hurd, though I'm sure Debian has some patches to theirs, since it identifies as Debian GLIBC 2.36-10~0.

**Comment by johnsonjh** [comment]
FWIW, I upgraded from 2023 (20230606T000000Z) to the latest snapshot, and that didn't change anything.

**Comment by z3ntu** [comment]
Does the linker path `/tools-i686/lib/ld.so` exist?

**Comment by johnsonjh** [comment]
> Does the linker path `/tools-i686/lib/ld.so` exist?

@z3ntu 

Good call.  No, it does not.

Creating the directory on the Hurd system, and adding a symlink (`ln -s /lib/ld.so.1 /tools-i686/lib/ld.so`) fixes the problem.  Strange, I'd have assumed only the target paths (those on the right-hand side of the `->` in `ldd` output) would have been relevant!

Patching this path in the binaries is trivial as well, so now I have a workaround! Thank you!

Is this a bug, or expected behavior?

**Comment by z3ntu** [comment]
If the linker doesn't exist, it can never run. Ldd only shows the dynamically linked dependencies which doesn't include the actual linker.

The path for this linker is expected, all the tools including libc are built for /tools. There's even a patch for I think gcc in this repo that changes this linker path for cross-hurd.

**Comment by johnsonjh** [comment]
@z3ntu Thanks for explaining, it was my misunderstanding.  I'll be able to work with this just fine.  I guess I should try 64-bit Hurd next, and see what the state of that is.  I guess even if I can't get everything running I can make sure the cross-compiled binaries build without error now.

Thanks.
