### ISSUE TITLE
Unable to run the image

### ISSUE THREAD

**Issue by gyfleury** [flavioc/cross-hurd#23]
Hello,

I used to run the image but this time if i run the image that i build i get this error.

![qemu](https://github.com/flavioc/cross-hurd/assets/35499992/8ff09b57-6f01-4916-9f0d-62e66169bb89)

any ring bell?

**Comment by flavioc** [comment]
You are likely using more than 1GB. PAE is the problem so I disabled it.

**Comment by gyfleury** [comment]
thanks it was that
