### ISSUE TITLE
Running without root

### ISSUE THREAD

**Issue by z3ntu** [flavioc/cross-hurd#4]
The **bootstrap** stage works fine without root when you prepend [these 3 lines](https://github.com/flavioc/cross-hurd/blob/master/bootstrap.sh#L228-L230) with `sudo`.

The **compile** stage fails at the `install_gnumach` section because the [`--exec-prefix=`](https://github.com/flavioc/cross-hurd/blob/master/compile.sh#L62) instruction tells gnumach to install to `/boot` (specifically `$exec_prefix/boot/gnumach` gets created).
The next part is `install_hurd` where the Makefiles try to run chown `/tools/libexec/_inst.12345_` but fails.

**Comment by flavioc** [comment]
I've tried the scripts recently without blanket root access for bootstrap.sh and compile.sh and things work fine. create-image.sh still requires root.

If it does not work, please reopen the issue.
