### ISSUE TITLE
List of dependencies

### ISSUE THREAD

**Issue by z3ntu** [flavioc/cross-hurd#5]
A full list of dependencies would be nice.

very incomplete list:
grub-pc-bin kpartx

**Comment by Gooberpatrol66** [comment]
Is your fork of cross-hurd still maintained? I don't think this one is.

**Comment by z3ntu** [comment]
My branch worked for me last time I used it (so around Nov 2017).

**Comment by Gooberpatrol66** [comment]
Would you be able to help me with something? I'm trying to fix #9, but I haven't figured out how. I believe I'm using your "patches" branch. Could anything have changed since you used it that would break the install?

**Comment by z3ntu** [comment]
Yeah quite some stuff changed. Your best bet would be to use upstream/mainline glibc instead of the specific Hurd glibc because some part (I don't remember if it's gnumach, hurd or whatever) needs stuff that is not present in the 2.23 glibc (in the hurd repo). But currently there seems to be a small problem with that mainline glibc that makes booting the image fail.

**Comment by z3ntu** [comment]
Closing this one, kpartx isn't needed anymore which was the most exotic dependency I think.
