### ISSUE TITLE
configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by Gooberpatrol66** [flavioc/cross-hurd#7]
[config.log](https://github.com/flavioc/cross-hurd/files/2034337/config.log)

**Comment by Gooberpatrol66** [comment]
Figured it out. C/CXXflags aren't in vars.sh but in bootstrap.sh. I would recommend changing the README.

**Comment by flavioc** [comment]
Fixed in e08dbec2a641029b0fed86cdaf062423ac07137a
